-- RodStack Supabase schema
-- Canonical definition:
--   supabase/migrations/20260729120000_auth_orgs_subscriptions.sql
--
-- Apply with Supabase CLI:
--   supabase db push
-- or paste the migration SQL into the Dashboard SQL editor.
--
-- Includes: profiles, organizations, organization_members, platform_admins,
-- subscriptions, subscription_overrides, feature_entitlements, audit_logs,
-- plan_preview_sessions, support_view_sessions, rodstack_workspaces, RLS, triggers.
